#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    turnSensor,     sensorNone)
#pragma config(Sensor, in2,    infraCollector, sensorReflection)
#pragma config(Sensor, dgtl1,  button1,        sensorTouch)
#pragma config(Sensor, dgtl2,  button2,        sensorTouch)
#pragma config(Sensor, dgtl3,  limitSwitch1,   sensorTouch)
#pragma config(Sensor, dgtl4,  limitSwitch2,   sensorTouch)
#pragma config(Sensor, dgtl5,  sonarSensor,    sensorSONAR_cm)
#pragma config(Sensor, dgtl8,  redLED1,        sensorDigitalOut)
#pragma config(Sensor, dgtl9,  redLED2,        sensorDigitalOut)
#pragma config(Sensor, dgtl10, redLED3,        sensorDigitalOut)
#pragma config(Sensor, dgtl11, redLED4,        sensorDigitalOut)
#pragma config(Sensor, I2C_1,  turnEncoder,    sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port3,           armMotor,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           turningMotor,  tmotorVex393_MC29, openLoop, encoderPort, I2C_1)
#pragma config(Motor,  port9,           rightDriveMotor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          leftDriveMotor, tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// These booleans define when each touch sensor has been activated
bool button1_pushed = false;
bool button2_pushed = false;
bool limitSwitch1_pushed = false;
bool limitSwitch2_pushed = false;

// A constant value defined for the wait1MSec function that corresponds to one second
const int oneSecond = 1000;

// LED light control values
const int OFF = 0;
const int ON  = 1;

// Monitors the given input for button1
void monitorInput() {
  if(SensorValue(button1) && !button1_pushed) {
    button1_pushed = true;
  }
  if(SensorValue(button2) && !button2_pushed) {
  	button2_pushed = true;
	}
	if(SensorValue(limitSwitch1) && !limitSwitch1_pushed) {
    limitSwitch1_pushed = true;
  }
  if(SensorValue(limitSwitch2) && !limitSwitch2_pushed) {
    limitSwitch2_pushed = true;
  }
}

// Initializes the status of the Red LEDs to OFF
void initLightStatus()
{
  // Turn off the red LED
  SensorValue(redLED1) = OFF;
  SensorValue(redLED2) = OFF;
  SensorValue(redLED3) = OFF;
  SensorValue(redLED4) = OFF;
}


// The following functions perform tasks required for Milestone 3:

// This function detects when the robot hits a wall using the limit switches and touch sensors
void detectWalls() {
	// Robot moves forward
	motor[leftDriveMotor] = 50;
	motor[rightDriveMotor] = 50;

	monitorInput();


	// Activates the fourth Red LED if one of the touch sensors has been pushed
	if(button1_pushed || button2_pushed || limitSwitch1_pushed || limitSwitch2_pushed) {
		SensorValue(redLED4) = ON;

		// Set the drive motors off and wait 3 seconds
		motor[leftDriveMotor] = 0;
		motor[rightDriveMotor] = 0;
		wait1Msec(oneSecond * 3);

		// Clear all button flags
		button1_pushed = false;
		button2_pushed = false;
		limitSwitch1_pushed = false;
		limitSwitch2_pushed = false;
	}
}

// The main function calls each function required for the specified behaviour of wall detection in Milestone 3
task main()
{
	while(true) {
		// This initializes the status of the Red LEDs
		initLightStatus();

		monitorInput();

		detectWalls();
	}
}
