#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    turnSensor,     sensorNone)
#pragma config(Sensor, in2,    infraCollector, sensorReflection)
#pragma config(Sensor, dgtl1,  button1,        sensorTouch)
#pragma config(Sensor, dgtl2,  button2,        sensorTouch)
#pragma config(Sensor, dgtl3,  limitSwitch1,   sensorTouch)
#pragma config(Sensor, dgtl4,  limitSwitch2,   sensorTouch)
#pragma config(Sensor, dgtl5,  sonarSensor,    sensorSONAR_cm)
#pragma config(Sensor, dgtl8,  redLED1,        sensorDigitalOut)
#pragma config(Sensor, dgtl9,  redLED2,        sensorDigitalOut)
#pragma config(Sensor, dgtl10, redLED3,        sensorDigitalOut)
#pragma config(Sensor, dgtl11, redLED4,        sensorDigitalOut)
#pragma config(Sensor, I2C_1,  turnEncoder,    sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port3,           armMotor,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           turningMotor,  tmotorVex393_MC29, openLoop, encoderPort, I2C_1)
#pragma config(Motor,  port9,           rightDriveMotor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          leftDriveMotor, tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// These booleans define when each touch sensor has been activated
bool button1_pushed = false;
bool button2_pushed = false;
bool limitSwitch1_pushed = false;
bool limitSwitch2_pushed = false;

// A constant value defined for the wait1MSec function that corresponds to one second
const int oneSecond = 1000;

// LED light control values
const int OFF = 0;
const int ON  = 1;

const int CableConnectionDistance = 20;

// The ideal distance for cable connection
//const int minCableConnectionDistance = 25;
//const int maxCableConnectionDistance = 15;

// The value if the Ultrasonic Range Finder cannot see the target
const int noObject = -1;

// Monitors the given input for button1
void monitorInput() {
  if(SensorValue(button1) && !button1_pushed) {
    button1_pushed = true;
  }
}

// Initializes the status of the Red LEDs to OFF
void initLightStatus()
{
  // Turn off the red LED
  SensorValue(redLED1) = OFF;
  SensorValue(redLED2) = OFF;
  SensorValue(redLED3) = OFF;
  SensorValue(redLED4) = OFF;
}


// The following functions perform tasks required for Milestone 3:

// This function detects the distance to the target object and signals whether or not the robot is in position to connect cable
void distanceToTarget() {
	// The Ultrasonic Range Finder determines that the target is too far away for cable connection
	if(SensorValue(sonarSensor) > CableConnectionDistance) {
		// Turns the second Red LED on for 3 seconds to signal that the target is not in position for connection
		SensorValue(redLED2) = ON;
		wait1Msec(oneSecond * 5);
		SensorValue(redLED2) = OFF;
	}
	// The Ultrasonic Range Finder determines that the target is the ideal distance away for cable connection
	else if((SensorValue(sonarSensor) < 20) && (SensorValue(sonarSensor) > 15)) {
		// Flashes the third Red LED to signal that the target is in position for connection
		int i; // Loop variable
		for(i = 0; i < 10; i++) {
			SensorValue(redLED3) = ON;
			wait1Msec(oneSecond * 0.2);
			SensorValue(redLED3) = OFF;
			wait1Msec(oneSecond * 0.2);
		}
	}
	// The Ultrasonic Range Finder determines that the target is too close for cable connection
	else if(SensorValue(sonarSensor) < CableConnectionDistance) {
		// Turns the second Red LED on for 3 seconds to signal that the target is not in position for connection
		SensorValue(redLED2) = ON;
		wait1Msec(oneSecond * 5);
		SensorValue(redLED2) = OFF;
	}
}


// The main function calls each function required for the specified behaviour of determining distance to target in Milestone 3
task main() {
	while(true) {
		// This initializes the value of the Red LED
		initLightStatus();

		monitorInput();

		// Calls the distance to target function and performs its intended operation
		distanceToTarget();

		// Clears button flags
		button1_pushed = false;
		button2_pushed = false;
		limitSwitch1_pushed = false;
		limitSwitch2_pushed = false;
	}
}
